#!/usr/bin/env python3
"""
Cognitive Shuffling CLI — speaks a random word from words.txt every 5–6 seconds via macOS `say`.
Reads words from words.txt next to this script (e.g. generated by filter_neutral_words.py).
Run in the foreground; stop with Ctrl+C. To run in background: nohup python3 cognitive_shuffle.py &
To stop when running in background: pkill -f cognitive_shuffle
"""
import random
import subprocess
import sys
import time
from pathlib import Path


def check_say() -> None:
    """Verify macOS `say` is available; exit with message if not."""
    result = subprocess.run(
        ["say", ""],
        capture_output=True,
        timeout=2,
    )
    if result.returncode != 0:
        print("macOS `say` not found or failed. This app requires macOS.", file=sys.stderr)
        sys.exit(1)


def load_words() -> list[str]:
    """Load word list from words.txt next to this script."""
    script_dir = Path(__file__).resolve().parent
    words_file = script_dir / "words.txt"
    if not words_file.is_file():
        print(
            f"words.txt not found at {words_file}. Run filter_neutral_words.py to create it.",
            file=sys.stderr,
        )
        sys.exit(1)
    try:
        raw = words_file.read_text(encoding="utf-8")
    except OSError as e:
        print(f"Cannot read {words_file}: {e}", file=sys.stderr)
        sys.exit(1)
    words = [w.strip() for w in raw.splitlines() if w.strip()]
    if not words:
        print("words.txt is empty. Run filter_neutral_words.py to populate it.", file=sys.stderr)
        sys.exit(1)
    return words


def main() -> None:
    check_say()
    words = load_words()
    print("Cognitive shuffling started. One word every 5–6 seconds. Stop with Ctrl+C.", flush=True)
    try:
        while True:
            word = random.choice(words)
            subprocess.run(["say", word], check=False)
            time.sleep(random.uniform(5, 6))
    except KeyboardInterrupt:
        print("\nStopped.", flush=True)


if __name__ == "__main__":
    main()
