#!/usr/bin/env python3
"""
Cognitive Shuffling CLI — speaks a random word from words.txt every 5–6 seconds via pyttsx3.
Reads words from words.txt next to this script (e.g. generated by filter_neutral_words.py).
Uses the system speech engine directly, which is lighter than RealtimeTTS for one-word playback.
Run in the foreground; stop with Ctrl+C. To run in background: nohup python3 cognitive_shuffle.py &
To stop when running in background: pkill -f cognitive_shuffle
"""
import random
import sys
import time
from pathlib import Path

SPEECH_RATE_WPM = 120

try:
    import pyttsx3
except ImportError as e:
    print(
        f"pyttsx3 not available: {e}\nInstall with: pip install -r requirements.txt",
        file=sys.stderr,
    )
    sys.exit(1)


def init_tts() -> pyttsx3.Engine:
    """Create the system TTS engine; exit with message on failure."""
    try:
        engine = pyttsx3.init()
        engine.setProperty("rate", SPEECH_RATE_WPM)
        return engine
    except Exception as e:
        print(
            f"System TTS failed to start: {e}. Install with: pip install -r requirements.txt",
            file=sys.stderr,
        )
        sys.exit(1)


def load_words() -> list[str]:
    """Load word list from words.txt next to this script."""
    script_dir = Path(__file__).resolve().parent
    words_file = script_dir / "words.txt"
    if not words_file.is_file():
        print(
            f"words.txt not found at {words_file}. Run filter_neutral_words.py to create it.",
            file=sys.stderr,
        )
        sys.exit(1)
    try:
        raw = words_file.read_text(encoding="utf-8")
    except OSError as e:
        print(f"Cannot read {words_file}: {e}", file=sys.stderr)
        sys.exit(1)
    words = [w.strip() for w in raw.splitlines() if w.strip()]
    if not words:
        print("words.txt is empty. Run filter_neutral_words.py to populate it.", file=sys.stderr)
        sys.exit(1)
    return words


def main() -> None:
    engine = init_tts()
    words = load_words()
    print("Cognitive shuffling started. One word every 5–6 seconds. Stop with Ctrl+C.", flush=True)
    try:
        while True:
            word = random.choice(words)
            engine.say(word)
            engine.runAndWait()
            time.sleep(random.uniform(5, 6))
    except KeyboardInterrupt:
        print("\nStopped.", flush=True)


if __name__ == "__main__":
    main()
